name = "ofc-signaling"
main = "worker/worker.ts"
compatibility_date = "2024-06-15"

[durable_objects]
bindings = [{ name = "ROOM", class_name = "RoomDurableObject" }]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["RoomDurableObject"]

[dev]
port = 8787
